server:
  port: 8081
spring:
  application:
    name: amqp-message-sender
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
rabbitmq:
  exchange:
    name: user.exchange
  queue:
    name: user.queue
  routing:
    key: user.routingkey
logging:
  level:
    com.medori42: DEBUG
    org.springframework.amqp: INFO